export type ColorScheme = 'dark' | 'light';

const shared = {
  radiusCollapsed: '999px',
  radiusL2: '32px',
  radiusL3: '24px',
  radiusSection: '16px',
  radiusControl: '12px',
  radiusChip: '999px',
  focusWidth: '2px',
  space1: '4px',
  space2: '8px',
  space3: '12px',
  space4: '16px',
  space5: '20px',
  space6: '24px',
  space8: '32px',
  controlMin: '44px',
  taskSwitcherRow: '52px',
  nodeMenuWidth: '208px',
  motionFast: '160ms',
  motionContent: '190ms',
  motionWindow: '200ms',
  fontUi: "'Segoe UI Variable', 'Microsoft YaHei UI', 'Segoe UI', system-ui, sans-serif",
  fontUtility: "'Cascadia Mono', 'Consolas', monospace"
} as const;

export const DESIGN_TOKENS = {
  dark: {
    ...shared,
    surfaceTint: 'rgba(10, 12, 15, 0.78)',
    surfaceFallback: '#111318',
    surfaceRaised: 'rgba(255, 255, 255, 0.06)',
    surfaceHover: 'rgba(255, 255, 255, 0.10)',
    surfacePressed: 'rgba(255, 255, 255, 0.14)',
    surfaceOverlay: 'rgba(8, 10, 13, 0.88)',
    borderSubtle: 'rgba(255, 255, 255, 0.10)',
    borderStrong: 'rgba(255, 255, 255, 0.18)',
    textPrimary: '#F5F7FA',
    textSecondary: '#B8BDC7',
    textTertiary: '#858B96',
    accent: '#64D2FF',
    accentText: '#061117',
    completed: '#32D74B',
    inProgress: '#64D2FF',
    pending: '#FFD60A',
    cancelled: '#858B96',
    critical: '#FF453A',
    high: '#FF9F0A',
    normal: '#8E8E93',
    low: '#858B96',
    danger: '#FF6961',
    shadow: 'rgba(3, 7, 12, 0.42)',
    selection: 'rgba(100, 210, 255, 0.28)'
  },
  light: {
    ...shared,
    surfaceTint: 'rgba(246, 247, 250, 0.84)',
    surfaceFallback: '#F2F4F7',
    surfaceRaised: 'rgba(255, 255, 255, 0.72)',
    surfaceHover: 'rgba(17, 19, 24, 0.05)',
    surfacePressed: 'rgba(17, 19, 24, 0.08)',
    surfaceOverlay: 'rgba(246, 247, 250, 0.92)',
    borderSubtle: 'rgba(17, 19, 24, 0.10)',
    borderStrong: 'rgba(17, 19, 24, 0.18)',
    textPrimary: '#15171A',
    textSecondary: '#5B616B',
    textTertiary: '#656C76',
    accent: '#0078D4',
    accentText: '#F8FBFF',
    completed: '#16843A',
    inProgress: '#0078D4',
    pending: '#8A6500',
    cancelled: '#656C76',
    critical: '#C62828',
    high: '#A65300',
    normal: '#6D737C',
    low: '#656C76',
    danger: '#B42318',
    shadow: 'rgba(40, 52, 68, 0.20)',
    selection: 'rgba(0, 120, 212, 0.20)'
  }
} as const;

const cssNames: Record<keyof typeof DESIGN_TOKENS.dark, string> = {
  radiusCollapsed: '--radius-collapsed',
  radiusL2: '--radius-l2',
  radiusL3: '--radius-l3',
  radiusSection: '--radius-section',
  radiusControl: '--radius-control',
  radiusChip: '--radius-chip',
  focusWidth: '--focus-width',
  space1: '--space-1',
  space2: '--space-2',
  space3: '--space-3',
  space4: '--space-4',
  space5: '--space-5',
  space6: '--space-6',
  space8: '--space-8',
  controlMin: '--control-min',
  taskSwitcherRow: '--task-switcher-row',
  nodeMenuWidth: '--node-menu-width',
  motionFast: '--motion-fast',
  motionContent: '--motion-content',
  motionWindow: '--motion-window',
  fontUi: '--font-ui',
  fontUtility: '--font-utility',
  surfaceTint: '--surface-tint',
  surfaceFallback: '--surface-fallback',
  surfaceRaised: '--surface-raised',
  surfaceHover: '--surface-hover',
  surfacePressed: '--surface-pressed',
  surfaceOverlay: '--surface-overlay',
  borderSubtle: '--border-subtle',
  borderStrong: '--border-strong',
  textPrimary: '--text-primary',
  textSecondary: '--text-secondary',
  textTertiary: '--text-tertiary',
  accent: '--accent',
  accentText: '--accent-text',
  completed: '--status-completed',
  inProgress: '--status-in-progress',
  pending: '--status-pending',
  cancelled: '--status-cancelled',
  critical: '--urgency-critical',
  high: '--urgency-high',
  normal: '--urgency-normal',
  low: '--urgency-low',
  danger: '--danger',
  shadow: '--shadow-color',
  selection: '--selection-color'
};

export function designTokenCssVariables(scheme: ColorScheme): Record<string, string> {
  const tokens = DESIGN_TOKENS[scheme];
  return Object.fromEntries(
    (Object.keys(tokens) as Array<keyof typeof tokens>).map((key) => [cssNames[key], tokens[key]])
  );
}
